In [1]:
import numpy as np
import pandas as pd

In [2]:
timestamp_begin_january = 1483228800
timestamp_end_november = 1512086399
timestamp_begin_december = 1512086400
timestamp_end_december = 1514764800
timestamp_per_day = 86400

min_orders_per_day = 0
max_orders_per_day = 500

min_user_id = 1000
max_user_id = 5000

In [3]:
class event:
    def __init__(self, eventid, name):
        self.eventid = eventid
        self.name = name

homepage = event(0, 'homepage')
menu_page = event(1, 'menu page')
log_in = event(2, 'log in')
basket_overview = event(3, 'basket overview')
check_out = event(4, 'check out')
confirm_order = event(5, 'confirm order')
order_completed = event(6, 'order completed')
no_event = event(7, 'no event')

all_events = [homepage, menu_page, log_in, basket_overview, check_out, confirm_order, order_completed]

In [4]:
#create dataframe 

def pick_event(previous_event):
    if previous_event == menu_page:
        random_select = np.random.randint(0, 15, size=1)[0]
        if random_select == 5 or random_select == 7:
            current_event = log_in
        elif random_select == 3 or random_select == 10 or random_select == 14:
            current_event = 'break'
        else: 
            current_event = menu_page
    else:
        current_event = all_events[previous_event.eventid + 1]
    return current_event

def one_order(current_user_id, current_time_stamp):
    df_new_order = pd.DataFrame(columns=('user_id', 'timestamp', 'event_id', 'event_name', 'churn'))
    event = homepage
    df_new_order_new_row = pd.DataFrame([[current_user_id, current_time_stamp, event.eventid, event.name, churn]], columns=('user_id', 'timestamp', 'event_id', 'event_name', 'churn'))
    df_new_order = df_new_order_new_row.append(df_new_order, ignore_index=True)
    number_of_klicks = 0
    while number_of_klicks < 20:
        event = pick_event(event)
        if event == 'break':
            break
        current_time_stamp = current_time_stamp + np.random.randint(0, 900, size=1)[0]
        df_new_order_new_row = pd.DataFrame([[current_user_id, current_time_stamp, event.eventid, event.name, churn]], columns=('user_id', 'timestamp', 'event_id', 'event_name', 'churn'))
        df_new_order = df_new_order.append(df_new_order_new_row, ignore_index=True)
        if event == order_completed:
            break
    return df_new_order

def append_df(timestamp_begin_day, timestamp_end_day, df_all_orders):
    orders_per_day = np.random.randint(min_orders_per_day, max_orders_per_day, size=1)[0]
    orders_per_day_created = 0
    while orders_per_day_created < orders_per_day:
        current_time_stamp = np.random.randint(timestamp_begin_day, timestamp_end_day, size=1)[0]
        current_user_id = np.random.randint(min_user_id, max_user_id, size=1)[0]
        df_new_order = one_order(current_user_id, current_time_stamp)
        df_all_orders = df_all_orders.append(df_new_order, ignore_index=True)
        orders_per_day_created += 1
    return df_all_orders

#-----------------------------run----------------------------#
df_all_orders_until_december = pd.DataFrame(columns=('user_id', 'timestamp', 'event_id', 'event_name', 'churn'))
df_all_orders_from_december = pd.DataFrame(columns=('user_id', 'timestamp', 'event_id', 'event_name', 'churn'))
day_of_the_year = 0
churn = 0
while True:
    print day_of_the_year
    timestamp_begin_day = timestamp_begin_january + day_of_the_year * timestamp_per_day
    timestamp_end_day = timestamp_begin_day + timestamp_per_day
    df_all_orders_until_december = append_df(timestamp_begin_day, timestamp_end_day, df_all_orders_until_december)
    day_of_the_year += 1
    if timestamp_end_november <= (timestamp_begin_january + day_of_the_year * timestamp_per_day):
        break
        
while True:
    timestamp_begin_day = timestamp_begin_december + day_of_the_year * timestamp_per_day
    timestamp_end_day = timestamp_begin_day + timestamp_per_day
    df_all_orders_from_december = append_df(timestamp_begin_day, timestamp_end_day, df_all_orders_from_december)
    day_of_the_year += 1
    print day_of_the_year
    if timestamp_end_december <= (timestamp_begin_january + day_of_the_year * timestamp_per_day):
        break

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365

In [5]:
#df_all_orders_until_december

In [12]:
#df_all_orders_from_december

In [13]:
#calculate churn

def calculate_churn(df_all_orders_from_december, df_all_orders_until_december, timestamp_begin_december):
    churned_users = []
    for row in df_all_orders_from_december.iterrows():
        if row[1][1] > timestamp_begin_december:
            churned_users.append(row[1][0])
    for row in df_all_orders_until_december.iterrows():
        if row[1][0] in churned_users:
            row[1][4] = 1
            
calculate_churn(df_all_orders_from_december, df_all_orders_until_december, timestamp_begin_december)

In [14]:
df_all_orders_until_december.to_csv('churn_time_dependent_unsorted.csv', index = False)

In [15]:
df_all_orders_until_december.sort_values(by=['timestamp'])

       user_id   timestamp event_id       event_name churn
189       2147  1483229505        0         homepage     1
378       2400  1483229720        0         homepage     1
1055      2903  1483229853        0         homepage     1
1056      2903  1483229912        1        menu page     1
190       2147  1483229997        1        menu page     1
1746      2400  1483230117        0         homepage     1
1747      2400  1483230209        1        menu page     1
379       2400  1483230295        1        menu page     1
1748      2400  1483230454        1        menu page     1
1057      2903  1483230512        1        menu page     1
2357      1432  1483230694        0         homepage     1
191       2147  1483230755        1        menu page     1
762       1222  1483230759        0         homepage     1
1058      2903  1483230990        1        menu page     1
763       1222  1483230996        1        menu page     1
781       2342  1483230998        0         homepage     1
764       1222  1483231044        1        menu page     1
587       2706  1483231094        0         homepage     1
765       1222  1483231101        1        menu page     1
1749      2400  1483231204        1        menu page     1
1750      2400  1483231276        2           log in     1
1092      2930  1483231321        0         homepage     1
1267      3354  1483231328        0         homepage     1
1751      2400  1483231329        3  basket overview     1
192       2147  1483231417        1        menu page     1
1093      2930  1483231471        1        menu page     1
1059      2903  1483231492        1        menu page     1
2358      1432  1483231553        1        menu page     1
782       2342  1483231579        1        menu page     1
1268      3354  1483231645        1        menu page     1
...        ...         ...      ...              ...   ...
493009    3889  1512084056        1        menu page     1
493039    3456  1512084181        0         homepage     1
493099    3437  1512084378        1        menu page     0
493010    3889  1512084768        2           log in     1
493040    3456  1512084925        1        menu page     1
493011    3889  1512085190        3  basket overview     1
492961    1045  1512085446        0         homepage     1
493200    4038  1512085595        0         homepage     1
493020    4252  1512085952        0         homepage     1
493012    3889  1512086001        4        check out     1
493201    4038  1512086042        1        menu page     1
492962    1045  1512086275        1        menu page     1
492963    1045  1512086306        1        menu page     1
493202    4038  1512086395        1        menu page     1
493013    3889  1512086575        5    confirm order     1
493021    4252  1512086583        1        menu page     1
492964    1045  1512086758        2           log in     1
492965    1045  1512086928        3  basket overview     1
493014    3889  1512087237        6  order completed     1
493022    4252  1512087305        1        menu page     1
493023    4252  1512087320        1        menu page     1
492966    1045  1512087697        4        check out     1
493024    4252  1512087799        1        menu page     1
493025    4252  1512087834        2           log in     1
492967    1045  1512088163        5    confirm order     1
493026    4252  1512088325        3  basket overview     1
492968    1045  1512088471        6  order completed     1
493027    4252  1512088624        4        check out     1
493028    4252  1512089070        5    confirm order     1
493029    4252  1512089919        6  order completed     1

[493346 rows x 5 columns]

In [16]:
df_all_orders_from_december.sort_values(by=['timestamp'])

      user_id   timestamp event_id       event_name churn
869      4397  1540944021        0         homepage     0
1592     2489  1540944055        0         homepage     0
107      2136  1540944089        0         homepage     0
377      4380  1540944125        0         homepage     0
378      4380  1540944151        1        menu page     0
1593     2489  1540944450        1        menu page     0
870      4397  1540944458        1        menu page     0
108      2136  1540944563        1        menu page     0
871      4397  1540944616        1        menu page     0
531      1983  1540944629        0         homepage     0
532      1983  1540944665        1        menu page     0
109      2136  1540944763        1        menu page     0
379      4380  1540944777        1        menu page     0
1124     1994  1540944811        0         homepage     0
1125     1994  1540945163        1        menu page     0
1594     2489  1540945273        2           log in     0
546      3943  1540945324        0         homepage     0
533      1983  1540945413        1        menu page     0
1126     1994  1540945498        1        menu page     0
534      1983  1540945580        1        menu page     0
961      4079  1540945616        0         homepage     0
547      3943  1540945677        1        menu page     0
1595     2489  1540945762        3  basket overview     0
548      3943  1540945879        1        menu page     0
962      4079  1540945985        1        menu page     0
1596     2489  1540946207        4        check out     0
535      1983  1540946363        1        menu page     0
963      4079  1540946377        1        menu page     0
964      4079  1540946434        1        menu page     0
179      1076  1540946594        0         homepage     0
...       ...         ...      ...              ...   ...
46801    2611  1543620527        1        menu page     0
46482    3438  1543620702        0         homepage     0
46470    2518  1543620703        4        check out     0
46487    1983  1543620785        0         homepage     0
46488    1983  1543621044        1        menu page     0
47124    3333  1543621045        1        menu page     0
46483    3438  1543621312        1        menu page     0
46489    1983  1543621353        1        menu page     0
46471    2518  1543621405        5    confirm order     0
46421    3343  1543621472        0         homepage     0
47125    3333  1543621481        1        menu page     0
46484    3438  1543621483        1        menu page     0
46490    1983  1543621496        1        menu page     0
46535    3562  1543621721        0         homepage     0
46422    3343  1543621915        1        menu page     0
46472    2518  1543622114        6  order completed     0
47039    3524  1543622171        0         homepage     0
47040    3524  1543622176        1        menu page     0
46536    3562  1543622289        1        menu page     0
46423    3343  1543622520        1        menu page     0
46424    3343  1543622558        1        menu page     0
46425    3343  1543623012        1        menu page     0
46537    3562  1543623118        1        menu page     0
46426    3343  1543623267        2           log in     0
46427    3343  1543623718        3  basket overview     0
46538    3562  1543623940        1        menu page     0
46539    3562  1543624365        1        menu page     0
46428    3343  1543624376        4        check out     0
46429    3343  1543624917        5    confirm order     0
46430    3343  1543624967        6  order completed     0

[47204 rows x 5 columns]

In [17]:
df_all_orders_until_december.to_csv('churn_time_dependent_sorted.csv', index = False)